<?xml version="1.0" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.shafagh</groupId>
    <artifactId>shafagh</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>application</artifactId>
  <dependencies>
    <dependency>
      <groupId>com.shafagh</groupId>
      <artifactId>base-impl</artifactId>
    </dependency>
    <dependency>
      <groupId>com.shafagh</groupId>
      <artifactId>cif-impl</artifactId>
    </dependency>
    <dependency>
      <groupId>com.shafagh</groupId>
      <artifactId>dpst-impl</artifactId>
    </dependency>
    <dependency>
      <groupId>com.shafagh</groupId>
      <artifactId>loan-impl</artifactId>
    </dependency>
    <dependency>
      <groupId>com.shafagh</groupId>
      <artifactId>transaction-impl</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.tngtech.archunit</groupId>
      <artifactId>archunit-junit5</artifactId>
      <version>1.4.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
