spring:
  application:
    name: shafagh
  config:
    import:
      - classpath:bank/base.yml
      - classpath:bank/cif.yml
      - classpath:bank/dpst.yml
      - classpath:bank/loan.yml
      - classpath:bank/transaction.yml
  jpa:
    open-in-view: false
bank:
  oracle:
    host: ${ORACLE_HOST:CENTRALDB-19C.MODERNISC.COM}
    port: ${ORACLE_PORT:1521}
    sid: ${ORACLE_SID:centraldb}
  ddl-mode: validate
  dialect: org.hibernate.dialect.OracleDialect
