com.atomikos.icatch.enable_logging=true
com.atomikos.icatch.log_base_dir=.runtime/atomikos
com.atomikos.icatch.tm_unique_name=shafagh-demo-1
com.atomikos.icatch.default_jta_timeout=30000
com.atomikos.icatch.max_timeout=60000
