<?xml version="1.0" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.shafagh</groupId>
    <artifactId>shafagh</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <artifactId>base</artifactId>
  <packaging>pom</packaging>
  <modules>
    <module>base-api</module>
    <module>base-impl</module>
  </modules>
</project>
