-- Run while connected as SHFQ_DPST, on a dedicated test schema.
CREATE TABLE DEMO_ACCOUNT (
 ID VARCHAR2(36 CHAR) PRIMARY KEY,
 CUSTOMER_ID VARCHAR2(36 CHAR) NOT NULL,
 BALANCE NUMBER(19,2) DEFAULT 0 NOT NULL,
 VERSION NUMBER(19,0) DEFAULT 0 NOT NULL,
 CONSTRAINT DEMO_BALANCE_NONNEGATIVE CHECK (BALANCE >= 0)
);
CREATE TABLE DEMO_POSTING (
 OPERATION_ID VARCHAR2(36 CHAR) PRIMARY KEY,
 ACCOUNT_ID VARCHAR2(36 CHAR) NOT NULL,
 AMOUNT NUMBER(19,2) NOT NULL,
 CONSTRAINT DEMO_POSTING_ACCOUNT_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES DEMO_ACCOUNT(ID),
 CONSTRAINT DEMO_POSTING_POSITIVE CHECK (AMOUNT > 0)
);
