-- Run while connected as SHFQ_TRX, on a dedicated test schema.
CREATE TABLE DEMO_BANK_TRANSACTION (
 OPERATION_ID VARCHAR2(36 CHAR) PRIMARY KEY,
 ACCOUNT_ID VARCHAR2(36 CHAR) NOT NULL,
 AMOUNT NUMBER(19,2) NOT NULL,
 CONSTRAINT DEMO_TXN_POSITIVE CHECK (AMOUNT > 0)
);
