-- DBA review only. Apply on the correct PDB and check your Oracle 19c patch-level
-- XA recovery requirements. No application-schema table grants between modules.
-- Users must already exist; no passwords or user creation are included here.
GRANT SELECT ON SYS.DBA_PENDING_TRANSACTIONS TO SHFQ_CIF;
GRANT SELECT ON SYS.DBA_2PC_PENDING TO SHFQ_CIF;
GRANT SELECT ON SYS.DBA_2PC_NEIGHBORS TO SHFQ_CIF;
GRANT EXECUTE ON SYS.DBMS_XA TO SHFQ_CIF;
GRANT SELECT ON SYS.DBA_PENDING_TRANSACTIONS TO SHFQ_DPST;
GRANT SELECT ON SYS.DBA_2PC_PENDING TO SHFQ_DPST;
GRANT SELECT ON SYS.DBA_2PC_NEIGHBORS TO SHFQ_DPST;
GRANT EXECUTE ON SYS.DBMS_XA TO SHFQ_DPST;
GRANT SELECT ON SYS.DBA_PENDING_TRANSACTIONS TO SHFQ_TRX;
GRANT SELECT ON SYS.DBA_2PC_PENDING TO SHFQ_TRX;
GRANT SELECT ON SYS.DBA_2PC_NEIGHBORS TO SHFQ_TRX;
GRANT EXECUTE ON SYS.DBMS_XA TO SHFQ_TRX;
